printWidth: 80
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
quoteProps: consistent
trailingComma: none
bracketSpacing: true
bracketSameLine: true
arrowParens: always
htmlWhitespaceSensitivity: strict
