name: Tests & Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "{NVMRC}={cat .nvmrc}" >> $(cat .nvmrc)
        id: nvm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.0.1

      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run format && pnpm run build
