name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "{NVMRC}={cat .nvmrc}" >> $(cat .nvmrc)
        id: nvm

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.0.1

      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: keskinkaan/utiljs

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run lint && pnpm run build
