name: Publish
on:
  workflow_run:
    workflows: [Tests & Build]
    branches: [dev]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "{NVMRC}={cat .nvmrc}" >> $(cat .nvmrc)
        id: nvm

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      - run: pnpm install
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
